branches:
  only:
  - develop
  
sudo: false
dist: trusty
language: cpp

jobs:
  include:
  - stage: Build-C++
    name: OSX-XCode
    os: osx
    osx_image: xcode11.1
    script:
      - cd tools
      - cmake .
      - make
  - name: Linux-g++-5       
    os: linux
    dist: trusty
    env: "CC=gcc-5 && CXX=g++-5"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    script:
      - cd tools
      - cmake .
      - make

  - stage: Build-JavaScript       
    os: linux
    dist: trusty
    script:
      - git clone https://github.com/emscripten-core/emsdk.git
      - cd emsdk
      - ./emsdk install latest
      - ./emsdk activate latest
      - source ./emsdk_env.sh
      - cd ..
      - cd tools
      - emcc --version
