branches:
  only:
  - develop
  
sudo: false
dist: trusty
language: cpp

jobs:
  include:
  - stage: deploy
    name: emscripten
    os: linux
    dist: trusty
    env: "CC=gcc-5 && CXX=g++-5"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    script:
      - git clone https://github.com/emscripten-core/emsdk.git
      - cd emsdk
      - ./emsdk install latest
      - ./emsdk activate latest
      - source ./emsdk_env.sh
      - cd ..
      - ./deploy-develop.sh
